name: UnpackedArray
mode: native
level: compile
top_module: top
sources:
- top.sv
upstream:
  repository: https://github.com/chipsalliance/UHDM-integration-tests.git
  revision: 1bd3e0bb9797778570423f44dc848e1d14c6d75f
  path: tests/UnpackedArray
expected: fail
reason: 'RyuSim 2.0.5: /tmp/tmp.z0GtSuUght/top.cpp:40:8: error: no viable overloaded
  ''='''
