# XuanTie-C910 — cocotb testbench
TOPLEVEL_LANG = verilog
SIM = ryusim

VERILOG_SOURCES = $(wildcard rtl/*.sv) $(wildcard rtl/*.v)
TOPLEVEL = TODO_top_module
MODULE = test_TODO_module

include $(shell cocotb-config --makefiles)/Makefile.sim
