name: AluOps
mode: native
level: compile
top_module: dut
sources:
- dut.v
upstream:
  repository: https://github.com/chipsalliance/UHDM-integration-tests.git
  revision: 1bd3e0bb9797778570423f44dc848e1d14c6d75f
  path: tests/AluOps
expected: pass
